### ISSUE TITLE
Current project status (end of 2023)?

### ISSUE THREAD

**Issue by soares-sergio** [zephyrproject-rtos/python-devicetree#6]
Hi,

I'm interested in using this project. I would like to experiment with enabling support for `devicetree` in a non-zephyr codebase/project.

Is this project currently active? What's the current status and licensing?

Thanks!!!

**Comment by hongshui3000** [comment]
Same question, hope someone can answer it

**Comment by dottspina** [comment]
The python-devicetree library is actively developed and maintained, but is still hosted by the main [Zephyr-RTOS/zephyr](https://github.com/zephyrproject-rtos/zephyr) project, not here:
- for now, just ignore this repository ([some info about this](https://github.com/zephyrproject-rtos/zephyr/tree/main/scripts/dts))
- once you've cloned zephyr, you'll find the library at `zephyr/scripts/dts/python-devicetree`

The Zephyr license is Apache version 2, you can use python-devicetree in your own projects under these terms.

**Comment by soares-sergio** [comment]
Thank you so much!
